### ISSUE TITLE
Parser doesn't work well with default values

### ISSUE THREAD

**Issue by zoechi** [seaneagan/unscripted#100]
> You can give an argument a parser simply by giving it a type (such as int or DateTime) which has a static parse method

This doesn't work well with default values because `parser` is not called for the `default` value and therefore is sent as `String` (default only supports String) which collides if the parameter is of type `DateTime`.

**Comment by seaneagan** [comment]
Unscripted will use the actual parameter default value if there is one, so that must match the parameter's type (`DateTime` in this case).  And if you are using `defaultsTo`, it's no different.  So the default value is already in the form that the function expects it, and thus should not be parsed.  It uses `toString()` to convent it back to a String for the help text though.

So it looks like the problem you are running into is just that `DateTime` doesn't have any const constructors which you are able to use to set a default parameter value.

If #19 is fixed, then you'll be able to pass a non-const `defaultsTo`, but that it intended for more dynamic use cases, and will not be as convenient / DRY as the existing interface.

**Comment by zoechi** [comment]
Thanks for looking into it. I'll try it again.
